version: "3"
services:
  mongo:
    container_name: mongo-container-survey-app
    image: mongo:6
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  api:
    container_name: api-container-survey-app
    image: node:18
    working_dir: /usr/src/app
    command: bash -c "npm install --only=production && npm run debug"
    volumes:
      - ./dist/:/usr/src/app/dist/
      - ./pachage.json:/usr/src/app/package.json
    ports:
      - 5050:5050
      - 9222:9222
    depends_on:
      - mongo